### ISSUE TITLE
Bug : Food

### ISSUE THREAD

**Issue by Arkenny** [ZerdBG3/DnDontStarve#5]
Dry Pork Sausage and Spicy pork Sausage providing only one level of hunger.
Include a list of how much each food item provides for less confusion.

**Comment by FelipeRenault** [comment]
Ah, the examples I gave there might be misleading. I think the sausage **pile** gives 2 levels of satiation
A list of food x level is doable, but man that list would be big and just some huge manual work for me, spare me some pity 😖
